# !!!!!!!!!!!!! DONT USE THIS EXAMPLE FOR PRODUCTION! GO TO https://eventula.lan2play.de/admin/getting_started.html#create-your-docker-compose-yml-file AND GET THE FILES THERE !!!!!!!!!!!!!

version: "3.4"
services:
  eventula_manager_app:
    build:
      context: .
    volumes:
      - eventula_manager_storage:/web/html/storage
      - $PWD/resources/certs:/etc/nginx/certs
      - $PWD/resources/secrets:/run/secrets
    env_file: $PWD/src/.env
    container_name: eventula_manager_app
    networks:
      - lan
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  eventula_manager_database:
    image: mysql:9
    volumes:
      - eventula_manager_database:/var/lib/mysql
    env_file: $PWD/src/.env
    ports:
      - 3306:3306
    container_name: eventula_manager_database
    networks:
      - lan
    restart: unless-stopped
volumes:
  eventula_manager_database:
    name: eventula_manager_database  
  eventula_manager_storage:
    name: eventula_manager_storage
networks:
  lan:
    external: true
